# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateField()),
                ('hours', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='PowerActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_date', models.DateField(verbose_name='stamp date')),
                ('actual_dc', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PowerExpected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_dc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=2)),
                ('co_ordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Coordinates')),
            ],
        ),
        migrations.AddField(
            model_name='powerexpected',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Units'),
        ),
        migrations.AddField(
            model_name='poweractual',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Units'),
        ),
        migrations.AddField(
            model_name='performance',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Units'),
        ),
    ]
