# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerexpected',
            name='expected_dc',
            field=models.TextField(null=True),
        ),
    ]
